school_website/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('website/', include('website.urls'))
]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('rekrutacja/', views.rekrutacja_page, name='rekrutacja_page'),
    path('aktualności/', views.news_page, name='news_page'),
    path('informacje_dla_rodziców/', views.info_for_parent_page, name='info_parents_page'),
    path('sekretariat/', views.sekretariat_page, name='sekretariat_page'),
    path('zdjęcia/', views.photos_page, name='zdjęcia_page')
]

website/models.py
from django.db import models


# Create your models here.
class Nauczyciel(models.Model):
    name = models.CharField(max_length=50)
    day = models.CharField(max_length=20)
    time = models.CharField(max_length=20)
    room_number = models.IntegerField()

school_website/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

website/views.py
from django.shortcuts import render, get_object_or_404
from .models import Nauczyciel


# Create your views here.
def rekrutacja_page(request):
    return render(request, 'website/rekrutacja.html')


def news_page(request):
    return render(request, 'website/news.html')


def info_for_parent_page(request):
    teachers = Nauczyciel.objects.all()
    return render(request, 'website/info-parents.html', {'teachers': teachers})


def sekretariat_page(request):
    return render(request, 'website/sekretariat.html')


def photos_page(request):
    return render(request, 'website/zdjęcia.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Oficjalna Strona Internetowa Zsp Myszyniec"
    />
    <meta
      property="og:title"
      content="Zsp Myszyniec - Zespół Szkół Powiatowych w Myszyńcu"
    />
    <meta property="og:description" content="Kształć się w wybranym kierunku" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="http://" />
    <meta property="og:url" content="https://" />
    <title>ZSP MYSZYNIEC</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <nav class="block block--dark collapsible nav">
      <img
        src="{% static 'icons/menu.svg' %}"
        alt=""
        class="icon collapsible__toggler nav__toggler"
      />
      <div class="collapsible__content">
        <ul class="list nav__content">
          <li>
            <a href="/" style="color: #00d9ff; font-weight: 700"
              >Strona głowna</a
            >
          </li>
          <li><a href="{% url 'website:news_page' %}">Aktualności</a></li>
          <li><a href="{% url 'website:rekrutacja_page' %}">Rekrutacja</a></li>
          <li>
            <a href="{% url 'website:info_parents_page' %}"
              >Informacje dla rodziców</a
            >
          </li>
          <li>
            <a href="{% url 'website:sekretariat_page' %}">Sekretariat</a>
          </li>
          <li>
            <a href="{% url 'website:zdjęcia_page' %}">Zdjęcia</a>
          </li>
        </ul>
      </div>
    </nav>
    <section class="block block--dark">
      <div class="container grid grid--1x2 hero">
        <div class="hero__header">
          <h1>
            Zespół Szkół Powiatowych im. ks. Adama Bargielskiego w Myszyńcu
          </h1>
          <a
            class="btn btn--primary hero__button"
            href="https://app.lapentor.com/sphere/zespol-szkol-powiatowych-w-myszyncu"
            target="_blank"
            >Wirtualny Spacer</a
          >
        </div>
        <picture>
          <source
            type="image/webp"
            srcset="{% static 'images/main.webp' %} 1x, {% static 'images/main@2x.webp' %} 2x"
          />
          <source
            type="image/jpg"
            srcset="{% static 'images/main.jpg' %} 1x, {% static 'images/main@2x.jpg' %} 2x"
          />
          <img
            src="{% static 'images/main@2x.jpg' %}"
            alt="logo"
            class="hero__image"
          />
        </picture>
      </div>
    </section>
    <section class="block container education-block">
      <h2>Kierunki Kształcenia</h2>
      <div class="grid grid--1x2">
        <div class="education__content">
          <div class="education__item">
            <h3>Liceum</h3>
            <ul class="list">
              <li>Matematyka</li>
              <li>Biologia</li>
              <li>Angielski</li>
              <li>Geografia</li>
            </ul>
          </div>
        </div>
        <div class="education__content">
          <div class="education__item">
            <h3>Technikum</h3>
            <ul class="list">
              <li>Technik Informatyk (Klasa mundurowa)</li>
              <li>Technik Ochrony Środowiska</li>
              <li>Technik Agrobiznesu</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="education__content szkola-branzowa">
        <h3>Branżowa Szkoła I Stopnia</h3>
        <div class="grid grid--1x2">
          <div class="education__item">
            <ul class="list szkola-branzowa__list">
              <li>Cukiernik</li>
              <li>Elektromechanik</li>
              <li>Elektryk</li>
              <li>Fryzjer</li>
              <li>Krawiec</li>
              <li>Kucharz</li>
              <li>Mechanik pojazdów samochodowych</li>
              <li>Monter sieci, instalacji i urządzeń sanitarnych</li>
            </ul>
          </div>
          <div class="education__item">
            <ul class="list szkola-branzowa__list">
              <li>Piekarz</li>
              <li>Rolnik</li>
              <li>Wędliniarz</li>
              <li>Sprzedawca</li>
              <li>Stolarz</li>
              <li>Ślusarz</li>
              <li>Murarz-tynkarz</li>
              <li>Mechanik-operator pojazdów i maszyn rolniczych</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <footer class="block contact-block">
      <div class="container contact-block__content">
        <a href="tel: +48297721429" target="_blank"
          ><i class="fa-solid fa-phone"></i>+48297721429</a
        >
        <a
          href="mailto: zsp.myszyniec@powiatostrolecki.pl"
          target="_blank"
          class="contact-block__mail"
          ><i class="fa-solid fa-envelope"></i
          >zsp.myszyniec@powiatostrolecki.pl</a
        >
        <a
          href="https://www.google.com/maps/place/Zesp%C3%B3%C5%82+Szk%C3%B3%C5%82+Powiatowych+im.ks.+Adama+Bargielskiego+w+Myszy%C5%84cu/@53.3865742,21.341534,17z/data=!3m1!4b1!4m6!3m5!1s0x471e0f561d8ed33f:0xce5bfc54206343d6!8m2!3d53.386571!4d21.3441089!16s%2Fg%2F1hf9wnkqm?entry=ttu"
          target="_blank"
          class="contact-block__location"
          ><i class="fa-solid fa-location-dot"></i>07-430 Myszyniec, ul. Dzieci
          Polskich 5</a
        >
      </div>
    </footer>
    <script
      src="https://kit.fontawesome.com/ef2d73a8ee.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

website/templates/website/info-parents.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Informacje dla rodziców</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <nav class="block block--dark collapsible nav">
      <img
        src="{% static 'icons/menu.svg' %}"
        alt=""
        class="icon collapsible__toggler nav__toggler"
      />
      <div class="collapsible__content">
        <ul class="list nav__content">
          <li>
            <a href="/">Strona głowna</a>
          </li>
          <li><a href="{% url 'website:news_page' %}">Aktualności</a></li>
          <li><a href="{% url 'website:rekrutacja_page' %}">Rekrutacja</a></li>
          <li>
            <a
              href="{% url 'website:info_parents_page' %}"
              style="color: #00d9ff; font-weight: 700"
              >Informacje dla rodziców</a
            >
          </li>
          <li>
            <a href="{% url 'website:sekretariat_page' %}">Sekretariat</a>
          </li>
          <li>
            <a href="{% url 'website:zdjęcia_page' %}">Zdjęcia</a>
          </li>
        </ul>
      </div>
    </nav>
    <section class="block parents-info-block">
      <h2>Informacje dla rodziców</h2>
      <div class="container parents-info-block__header">
        <p>
          Zarząd Rady Rodziców przy Zespole Szkół Powiatowych im. ks. Adama
          Bargielskiego w Myszyńcu w roku szkolnym 2023/2024 tworzą
          przedstawiciele z trójek klasowych:
        </p>
        <ul class="list">
          <li>Przewodnicząca – Anna Wróblewska</li>
          <li>Z-ca przewodniczącej – Magdalena Siok</li>
          <li>Sekretarz – Joanna Pliszka</li>
          <li>Członek – Teresa Drężek</li>
          <li>Członek – Stanisław Drężek</li>
        </ul>
      </div>
      <div class="parents-info-block__content">
        <h3>Dni wolne od zajęć dydaktycznych w roku szkolnym 2023/2024:</h3>
        <ul class="list">
          <li>29 kwietnia 2024</li>
          <li>30 kwietnia 2024</li>
          <li>2 maja 2024</li>
          <li>6 maja 2024</li>
          <li>7 maja 2024</li>
          <li>8 maja 2024</li>
          <li>9 maja 2024</li>
          <li>31 maja 2024</li>
        </ul>
      </div>
      <h3 class="table__heading">
        Dni dostępności nauczycieli w szkole na rok szkolny 2023/2024:
      </h3>
      <div class="container block parents-info-block__table">
        <table class="info-table">
          <thead>
            <tr>
              <th style="text-align: left">Nazwisko</th>
              <th>Dzień</th>
              <th>Godz</th>
              <th>Sala</th>
            </tr>
          </thead>
          <tbody>
            {% for teacher in teachers %}
            <tr>
              <td style="text-align: left">{{ teacher.name }}</td>
              <td>{{ teacher.day }}</td>
              <td>{{ teacher.time }}</td>
              <td class="info-table__room">{{ teacher.room_number }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </section>
    <section class="block table-mobile">
      {% for teacher in teachers %}
      <div class="container table-mobile__content">
        <span>{{ teacher.name }}</span>
        <ul class="list">
          <li>{{ teacher.day }}</li>
          <li>{{ teacher.time }}</li>
          <li>Numer Sali: {{ teacher.room_number }}</li>
        </ul>
      </div>
      {% endfor %}
    </section>

    <footer class="block contact-block">
      <div class="container contact-block__content">
        <a href="tel: +48297721429" target="_blank"
          ><i class="fa-solid fa-phone"></i>+48297721429</a
        >
        <a
          href="mailto: zsp.myszyniec@powiatostrolecki.pl"
          target="_blank"
          class="contact-block__mail"
          ><i class="fa-solid fa-envelope"></i
          >zsp.myszyniec@powiatostrolecki.pl</a
        >
        <a
          href="https://www.google.com/maps/place/Zesp%C3%B3%C5%82+Szk%C3%B3%C5%82+Powiatowych+im.ks.+Adama+Bargielskiego+w+Myszy%C5%84cu/@53.3865742,21.341534,17z/data=!3m1!4b1!4m6!3m5!1s0x471e0f561d8ed33f:0xce5bfc54206343d6!8m2!3d53.386571!4d21.3441089!16s%2Fg%2F1hf9wnkqm?entry=ttu"
          target="_blank"
          class="contact-block__location"
          ><i class="fa-solid fa-location-dot"></i>07-430 Myszyniec, ul. Dzieci
          Polskich 5</a
        >
      </div>
    </footer>
    <script
      src="https://kit.fontawesome.com/ef2d73a8ee.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

website/templates/website/news.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Aktualności</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <nav class="block block--dark collapsible nav">
      <img
        src="{% static 'icons/menu.svg' %}"
        alt=""
        class="icon collapsible__toggler nav__toggler"
      />
      <div class="collapsible__content">
        <ul class="list nav__content">
          <li><a href="/">Strona głowna</a></li>
          <li>
            <a
              href="{% url 'website:news_page' %}"
              style="color: #00d9ff; font-weight: 700"
              >Aktualności</a
            >
          </li>
          <li><a href="{% url 'website:rekrutacja_page' %}">Rekrutacja</a></li>
          <li>
            <a href="{% url 'website:info_parents_page' %}"
              >Informacje dla rodziców</a
            >
          </li>
          <li>
            <a href="{% url 'website:sekretariat_page' %}">Sekretariat</a>
          </li>
          <li>
            <a href="{% url 'website:zdjęcia_page' %}">Zdjęcia</a>
          </li>
        </ul>
      </div>
    </nav>
    <section class="block news-block">
      <div class="container news-block__content">
        <div class="news-block__header">
          <h3 class="news-block__heading">Edukacja z wojskiem</h3>
          <span class="news-block__date">13 czerwca 2024</span>
        </div>
        <p>
          12 czerwca 2024 roku w naszej szkole dobyło się spotkanie z
          przedstawicielami Jednostki Wojskowej z Przasnysza. Podczas spotkania
          dowiedzieliśmy się o zagrożeniach jakie mogą nas spotkać w codziennym
          życiu. Zostaliśmy m.in., przeszkoleni jak udzielać pierwszej pomocy,
          jak zachować się w sytuacji zagrożenia, jakie są alarmy i jak na nie
          reagować oraz nauczyliśmy się jak postępować podczas pożaru. Mieliśmy
          również możliwość zapoznania się z wyposażeniem wojska używanego, np.
          podczas skażenia (specjalne kombinezony ochronne, maski gazowe).
          Dzięki temu spotkaniu zdobyliśmy ogromną wiedzę, która na pewno przyda
          nam się w przyszłości. Dziękujemy!
        </p>
      </div>
      <div class="container news-block__content">
        <div class="news-block__header">
          <h3 class="news-block__heading">DIECEZJALNY DZIEŃ DZIECKA</h3>
          <span class="news-block__date">10 czerwca 2024</span>
        </div>
        <p>
          08.06.2024r. – udział uczniów z klas I, II, III Liceum
          Ogólnokształcącego w charakterze wolontariuszy w 2. Diecezjalnym Dniu
          Dziecka. Już po raz drugi Parafia pw. Trójcy Przenajświętszej w
          Myszyńcu zorganizowała Diecezjalny Dzień Dziecka. Jak przed rokiem
          członkowie dziecięcych grup i wspólnot katolickich integrowali się w
          Kurpiowskiej Krainie w Wykrocie. Uczniowie z naszej szkoły w ramach
          wolontariatu pomagali w organizacji tego wydarzenia. Był to dla nas
          miło spędzony czas, który przyniósł nam wiele radości. Cieszymy się,
          że mogliśmy okazać nasze wsparcie i pomoc…
        </p>
      </div>
      <div class="container news-block__content">
        <div class="news-block__header">
          <h3 class="news-block__heading">MYSZYNIECKI ARCHIFEST</h3>
          <span class="news-block__date">10 czerwca 2024</span>
        </div>
        <p>
          07 czerwca 2024 w Regionalnym Centrum Kultury Kurpiowskiej odbył się
          1. Myszyniecki Archifest. Wzięli w nim udział uczniowie Liceum
          Ogólnokształcącego oraz Technikum Agrobiznesu. Pierwszym punktem
          Archifestu był spektakl multimedialny obrazów p. Piotra Kobrzyńskiego
          i ekfrazami p. Marii Pawłowskiej. Połączenie ze sobą twórczości tych
          dwojga artystów oraz oprawy muzycznej sprawiło, iż spektakl ten stał
          się niezapomnianym i niezwykłym doświadczeniem dla oglądających. Była
          to swego rodzaju podróż w głąb ludzkiej duszy… Drugim punktem programu
          były warsztaty pod hasłem „Kilka słów o Archiwach Społecznych”.
          Warsztaty te prowadził Animator Kultury RCKK p. Tomasz Mierzejek oraz
          p. Monika Kozłowska-dyrektor MGBP. Młodzież dowiedziała się , czym
          zajmują się archiwa społeczne, ile jest takich archiwów w naszym
          regionie, jakie zbiory obejmują archiwa społeczne, kto może zostać
          archiwistą oraz jak można zostać wolontariuszem w archiwum społecznym.
          Trzecim punktem programu było otwarcie wystawy pt. „Myszynieckie
          Zbiory Społeczne”, które zostały zgromadzone przez myszynieckie
          Archiwum Społeczne. Na zakończenie młodzież zwiedziła Multimedialne
          Muzeum w Dzwonnicy Myszynieckiej. Jak twierdzi młodzież, było to
          bardzo ciekawe doświadczenie, które uwrażliwiło ich artystycznie i
          wzbogaciło wiedzę z dziedziny dotychczas im nieznanej… Jesteśmy
          wdzięczni za możliwość wzięcia udziału w tak wspaniałym wydarzeniu:
          Uczniowie klas: ILO, II LO , III LO i I TA oraz opiekunowie: p. M.
          Olkowska, p.M.Batorska i p. A.Jachimczyk
        </p>
      </div>
    </section>
    <footer class="block contact-block">
      <div class="container contact-block__content">
        <a href="tel: +48297721429" target="_blank"
          ><i class="fa-solid fa-phone"></i>+48297721429</a
        >
        <a
          href="mailto: zsp.myszyniec@powiatostrolecki.pl"
          target="_blank"
          class="contact-block__mail"
          ><i class="fa-solid fa-envelope"></i
          >zsp.myszyniec@powiatostrolecki.pl</a
        >
        <a
          href="https://www.google.com/maps/place/Zesp%C3%B3%C5%82+Szk%C3%B3%C5%82+Powiatowych+im.ks.+Adama+Bargielskiego+w+Myszy%C5%84cu/@53.3865742,21.341534,17z/data=!3m1!4b1!4m6!3m5!1s0x471e0f561d8ed33f:0xce5bfc54206343d6!8m2!3d53.386571!4d21.3441089!16s%2Fg%2F1hf9wnkqm?entry=ttu"
          target="_blank"
          class="contact-block__location"
          ><i class="fa-solid fa-location-dot"></i>07-430 Myszyniec, ul. Dzieci
          Polskich 5</a
        >
      </div>
    </footer>
    <script
      src="https://kit.fontawesome.com/ef2d73a8ee.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

website/templates/website/rekrutacja.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Rekrutacja</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <nav class="block block--dark collapsible nav">
      <img
        src="{% static 'icons/menu.svg' %}"
        alt=""
        class="icon collapsible__toggler nav__toggler"
      />
      <div class="collapsible__content">
        <ul class="list nav__content">
          <li><a href="/">Strona głowna</a></li>
          <li><a href="{% url 'website:news_page' %}">Aktualności</a></li>
          <li>
            <a
              href="{% url 'website:rekrutacja_page' %}"
              style="color: #00d9ff; font-weight: 700"
              >Rekrutacja</a
            >
          </li>
          <li>
            <a href="{% url 'website:info_parents_page' %}"
              >Informacje dla rodziców</a
            >
          </li>
          <li>
            <a href="{% url 'website:sekretariat_page' %}">Sekretariat</a>
          </li>
          <li>
            <a href="{% url 'website:zdjęcia_page' %}">Zdjęcia</a>
          </li>
        </ul>
      </div>
    </nav>

    <article class="block recruitment-block">
      <h2 class="recruitment-block__heading">Rekrutacja</h2>
      <div class="recruitment-block__content">
        <div>
          <p>
            INFORMACJA DLA KANDYDATA O TERMINACH SKŁADANIA DOKUMENTÓW ROK
            SZKOLNY 2023-2024:
          </p>
          <ol class="recruitment-block__list">
            <li>
              Termin składania wniosków o przyjęcie: od
              <span>15 maja</span> 2024 do <span>29 maja</span> 2024 r. do
              godz.15:00
            </li>
            <li>
              Termin składania świadectw ukończenia szkoły podstawowej i
              zaświadczenia z egzaminu ósmoklasisty: od
              <span>3 lipca 2024 do 10 lipca 2024 do godz. 15:00.</span> Przy
              składaniu oryginalnych dokumentów kandydat przynosi również
              podpisane na odwrocie zdjęcie legitymacyjne -1szt.
            </li>
            <li>
              Od <span>15 maja 2024 r. do 22 lipca 2024</span> kandydatom,
              którzy dokonali wyboru kształcenia w danym zawodzie, wskazując
              szkołę jako szkołę pierwszego wyboru. w Technikum i Branżowej
              Szkole I Stopnia, dyrektor Zespołu Szkół Powiatowych w Myszyńcu
              wydaje skierowania na badanie lekarskie do lekarza medycyny pracy.
            </li>
            <li>
              Lista kandydatów zakwalifikowanych wywieszona będzie na drzwiach
              głównych szkoły dnia <span>19 lipca</span> 2024r.
            </li>
            <li>
              Lista kandydatów przyjętych wywieszona będzie na drzwiach głównych
              szkoły dnia <span>25 lipca</span> 2024r.
            </li>
          </ol>
        </div>
        <div>
          <p>
            DOKUMENTY POTRZEBNE DO ZAWARCIA UMOWY MŁODOCIANEGO PRACOWNIKA Z
            PRACODAWCĄ:
          </p>
          <ol class="recruitment-block__list">
            <li>Kserokopia świadectwa ukończenia szkoły podstawowej</li>
            <li>Wyciąg aktu urodzenia</li>
            <li>Numer pesel, dokładny adres zamieszkania</li>
            <li>
              Zaświadczenie o przyjęciu do szkoły ponadpodstawowej (dostępne w
              sekretariacie po ogłoszeniu wyników rekrutacji)
            </li>
            <li>
              Opinia z Poradni Psychologiczno-Pedagogicznej o możliwości
              podjęcia praktycznej nauki zawodu – jeśli uczeń nie ma ukończonego
              15 roku życia
            </li>
            <li>
              Skierowanie od pracodawcy na badania do lekarza medycyny pracy do
              podjęcia pracy w wybranym zawodzie
            </li>
            <li>
              Książeczka zdrowia (tzw. sanepidowska) podpisana przez
              uprawnionego lekarza rodzinnego
            </li>
          </ol>
        </div>
      </div>
      <div class="wniosek-container">
        <a
          href="{% static 'pdfs/WNIOSEK-O-PRZYJECIE-DO-SZKOLY-2024_2025.pdf' %}"
          download
          class="btn btn--primary wniosek__btn"
          >Wniosek o przyjęcie do szkoły ponadpodstawowej</a
        >
        <a
          href="{% static 'pdfs/WNIOSEK-O-PRZYJECIE-DO-SZKOLY-2024_2025.pdf' %}"
          download
          class="btn--pdf wniosek__btn-pdf"
          >Wniosek o przyjęcie do szkoły ponadpodstawowej<i
            class="fa-solid fa-file-pdf"
          ></i
        ></a>
      </div>
    </article>
    <footer class="block contact-block">
      <div class="container contact-block__content">
        <a href="tel: +48297721429" target="_blank"
          ><i class="fa-solid fa-phone"></i>+48297721429</a
        >
        <a
          href="mailto: zsp.myszyniec@powiatostrolecki.pl"
          target="_blank"
          class="contact-block__mail"
          ><i class="fa-solid fa-envelope"></i
          >zsp.myszyniec@powiatostrolecki.pl</a
        >
        <a
          href="https://www.google.com/maps/place/Zesp%C3%B3%C5%82+Szk%C3%B3%C5%82+Powiatowych+im.ks.+Adama+Bargielskiego+w+Myszy%C5%84cu/@53.3865742,21.341534,17z/data=!3m1!4b1!4m6!3m5!1s0x471e0f561d8ed33f:0xce5bfc54206343d6!8m2!3d53.386571!4d21.3441089!16s%2Fg%2F1hf9wnkqm?entry=ttu"
          target="_blank"
          class="contact-block__location"
          ><i class="fa-solid fa-location-dot"></i>07-430 Myszyniec, ul. Dzieci
          Polskich 5</a
        >
      </div>
    </footer>
    <script
      src="https://kit.fontawesome.com/ef2d73a8ee.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>